#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["CoreWebApi_App/CoreWebApi_App.csproj", "CoreWebApi_App/"]
RUN dotnet restore "CoreWebApi_App/CoreWebApi_App.csproj"
COPY . .
WORKDIR "/src/CoreWebApi_App"
RUN dotnet build "CoreWebApi_App.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CoreWebApi_App.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CoreWebApi_App.dll"]